services:

  postgres:
    image: postgres:16-alpine
    container_name: bank-account-transfers-postgres-db
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: bank_account_transfers_db
    volumes:
      - bank_account_transfers_postgres_data:/var/lib/postgresql/data
    networks:
      - bank_account_transfers_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d bank_account_transfers_db || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 10s

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.7.0
    ports:
      - '127.0.0.1:4568:4566'
    environment:
      SERVICES: kinesis
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      LS_LOG: ${LS_LOG:-debug}
      DATA_DIR: /var/lib/localstack  # <- Permite persistência no volume
    networks:
      - bank_account_transfers_network
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack:/etc/localstack/init/ready.d
      - bank_account_transfers_localstack_data:/var/lib/localstack  # <- Volume persistente

volumes:
  bank_account_transfers_postgres_data:
    name: bank-account-transfers-postgres-data
  bank_account_transfers_localstack_data:
    name: bank-account-transfers-localstack-data

networks:
  bank_account_transfers_network:
    name: bank-account-transfers-network
