version: '3.9'

services:
  bank-account-transfers-service:
    build:
      context: .
#    container_name: bank-account-transfers-service #TODO think about the docker image
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_account_transfers_db
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: admin_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop #TODO ARRUMAR ISSO PRA PRODUCAO
      SPRING_PROFILES_ACTIVE: dev  # 👈 Set the profile to dev
    ports:
      - "8080:8080"
    networks:
      - bank_account_transfers_network

  postgres:
    image: postgres:16-alpine
    container_name: bank_account_transfers_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: bank_account_transfers_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_account_transfers_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d bank_account_transfers_db || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  bank_account_transfers_network: