aws:
  access-key-id: test
  secret-key: test
  region: us-east-1
  kinesis:
    endpoint: 'http://localhost:4568'


spring:
  config:
    import: classpath:openapi-config.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_account_transfers_db
    username: admin
    password: admin_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # or "validate" if schema is already created
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

bank-account-service:
  api:
    v1:
      base-url: 'http://localhost:8090/'
      path-url: 'api/v1/bank-accounts/iban/{iban}'
