spring:
  config:
    import: classpath:openapi-config.yml
  datasource.url
#  datasource:
#    url: jdbc:postgresql://localhost:5432/bank_account_transfers_db
#    username: admin
#    password: admin_password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update # or "validate" if schema is already created
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true