spring:
  application:
    name: bank-account-transfers
#  locale:
#    default: "en"

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  #TODO adjust it for production
  jpa:
    hibernate:
      ddl-auto: create-drop  # For dev/testing only; use 'update' or 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

#TODO adjust it for production
bank-account-service:
  api:
    v1:
      base-url: 'http://localhost:8080/'
      path-url: 'api/v1/bank-accounts/iban/{iban}'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
    tags:
      application: bank-account-transfers
