spring:
  application:
    name: bank-account-transfers

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  #TODO adjust it for production
  jpa:
    hibernate:
      ddl-auto: create-drop  # For dev/testing only; use 'update' or 'validate' in production
    show-sql: false
    properties:
      hibernate:
        format_sql: true

aws:
  region: ${AWS_DEFAULT_REGION}
  kinesis:
    streams:
      request-internal-transfers:
        stream-name: request-internal-transfers

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

api:
  v1:
    bank-transfers:
      root-path: '/api/v1/bank-transfers'

client:
  api:
    bank-account-management:
      base-url: 'http://localhost:8090'

#TODO adjust it for production
bank-account-service:
  api:
    v1:
      base-url: 'http://localhost:8090/'
      path-url: 'api/v1/bank-accounts/iban/{iban}'

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, metrics, prometheus"
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 0.1, 0.3, 0.5, 1, 2, 5
