apiVersion: v1
kind: Pod
metadata:
  name: bank-account-transfers-pod
spec:
  containers:
    - name: bank-account-transfers-service
      image: bank-account-transfers:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
#        - name: DATABASE_URL
#          value: "jdbc:postgresql://172.18.0.3in:5432/bank_account_transfers_db"
#        - name: POSTGRES_USER
#          value: "admin"
#        - name: POSTGRES_PASSWORD
#          value: "admin_password"