apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bank-account-transfers-rs
  labels:
    app: bank-account-transfers
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: bank-account-transfers
  template:
    metadata:
      labels:
        app: bank-account-transfers
    spec:
      containers:
        - name: bank-account-transfers
          image: bank-account-transfers:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
#            - name: DATABASE_URL
#              value: "jdbc:postgresql://172.18.0.3:5432/bank_db"
#            - name: POSTGRES_USER
#              value: "admin"
#            - name: POSTGRES_PASSWORD
#              value: "password"
#            - name: REDIS_HOST
#              value: "redis"
