apiVersion: v1
kind: Pod
metadata:
  name: bank-account-transfers-pod
spec:
  containers:
    - name: bank-account-transfers
      image: jcondotta/bank-account-transfers:latest
      ports:
        - containerPort: 8080
      env:
        - name: DATASOURCE_URL
          value: jdbc:postgresql://192.168.1.39:5432/bank_account_transfers_db
        - name: DATASOURCE_USERNAME
          value: admin
        - name: DATASOURCE_PASSWORD
          value: admin_password