apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: bank-account-transfers
data:
  POSTGRES_DB: bank_account_transfers_db

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bank-account-transfers
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=   # Base64 for "admin"
  POSTGRES_PASSWORD: YWRtaW5fcGFzc3dvcmQ=   # Base64 for "admin_password"
